title: "Guillermo Correa - Contador Público"
description: "Explorando La IA en Contabilidad - Especialista en inteligencia artificial aplicada a la contabilidad"
baseurl: ""

url: "https://iacontabilidadguillermo.com"

permalink: pretty ← AÑADE ESTA LÍNEA


theme: minima
# ... el resto de tu configuración
